# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PROG1700_SourceCode\w0428722-OliveiraR\Final Project\CountriesOWG.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LabelChooseCountryList = QtWidgets.QLabel(self.centralwidget)
        self.LabelChooseCountryList.setGeometry(QtCore.QRect(20, 20, 249, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.LabelChooseCountryList.setFont(font)
        self.LabelChooseCountryList.setObjectName("LabelChooseCountryList")
        self.listWidgetShowCountry = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetShowCountry.setGeometry(QtCore.QRect(20, 40, 271, 511))
        self.listWidgetShowCountry.setObjectName("listWidgetShowCountry")
        self.rightViewFrame = QtWidgets.QFrame(self.centralwidget)
        self.rightViewFrame.setGeometry(QtCore.QRect(310, 40, 461, 511))
        self.rightViewFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightViewFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightViewFrame.setObjectName("rightViewFrame")
        self.labelPercentageWrldPop = QtWidgets.QLabel(self.rightViewFrame)
        self.labelPercentageWrldPop.setGeometry(QtCore.QRect(10, 410, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelPercentageWrldPop.setFont(font)
        self.labelPercentageWrldPop.setObjectName("labelPercentageWrldPop")
        self.labelAreaIn = QtWidgets.QLabel(self.rightViewFrame)
        self.labelAreaIn.setGeometry(QtCore.QRect(20, 270, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAreaIn.setFont(font)
        self.labelAreaIn.setObjectName("labelAreaIn")
        self.comboBoxSqMilesxSqKM = QtWidgets.QComboBox(self.rightViewFrame)
        self.comboBoxSqMilesxSqKM.setGeometry(QtCore.QRect(100, 270, 81, 22))
        self.comboBoxSqMilesxSqKM.setObjectName("comboBoxSqMilesxSqKM")
        self.comboBoxSqMilesxSqKM.addItem("")
        self.comboBoxSqMilesxSqKM.addItem("")
        self.pushButtonUpdatePop = QtWidgets.QPushButton(self.rightViewFrame)
        self.pushButtonUpdatePop.setGeometry(QtCore.QRect(260, 230, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonUpdatePop.setFont(font)
        self.pushButtonUpdatePop.setObjectName("pushButtonUpdatePop")
        self.labelCountryName = QtWidgets.QLabel(self.rightViewFrame)
        self.labelCountryName.setGeometry(QtCore.QRect(10, 10, 441, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelCountryName.setFont(font)
        self.labelCountryName.setObjectName("labelCountryName")
        self.labelPopulation = QtWidgets.QLabel(self.rightViewFrame)
        self.labelPopulation.setGeometry(QtCore.QRect(70, 200, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPopulation.setFont(font)
        self.labelPopulation.setObjectName("labelPopulation")
        self.groupBoxPopDens = QtWidgets.QGroupBox(self.rightViewFrame)
        self.groupBoxPopDens.setGeometry(QtCore.QRect(10, 310, 411, 91))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBoxPopDens.setFont(font)
        self.groupBoxPopDens.setObjectName("groupBoxPopDens")
        self.radioButtonPopPerSQMile = QtWidgets.QRadioButton(self.groupBoxPopDens)
        self.radioButtonPopPerSQMile.setGeometry(QtCore.QRect(10, 30, 131, 17))
        self.radioButtonPopPerSQMile.setObjectName("radioButtonPopPerSQMile")
        self.radioButtonPerSqKMPop = QtWidgets.QRadioButton(self.groupBoxPopDens)
        self.radioButtonPerSqKMPop.setGeometry(QtCore.QRect(10, 60, 131, 17))
        self.radioButtonPerSqKMPop.setObjectName("radioButtonPerSqKMPop")
        self.labelPopDensValue = QtWidgets.QLabel(self.groupBoxPopDens)
        self.labelPopDensValue.setGeometry(QtCore.QRect(280, 50, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelPopDensValue.setFont(font)
        self.labelPopDensValue.setObjectName("labelPopDensValue")
        self.lineEditPopulationValue = QtWidgets.QLineEdit(self.rightViewFrame)
        self.lineEditPopulationValue.setGeometry(QtCore.QRect(170, 200, 241, 20))
        self.lineEditPopulationValue.setObjectName("lineEditPopulationValue")
        self.labelPercentWPValue = QtWidgets.QLabel(self.rightViewFrame)
        self.labelPercentWPValue.setGeometry(QtCore.QRect(290, 410, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelPercentWPValue.setFont(font)
        self.labelPercentWPValue.setObjectName("labelPercentWPValue")
        self.labelTotalAreaValue = QtWidgets.QLabel(self.rightViewFrame)
        self.labelTotalAreaValue.setGeometry(QtCore.QRect(290, 290, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelTotalAreaValue.setFont(font)
        self.labelTotalAreaValue.setObjectName("labelTotalAreaValue")
        self.labelFlagIMG = QtWidgets.QLabel(self.rightViewFrame)
        self.labelFlagIMG.setGeometry(QtCore.QRect(76, 50, 331, 131))
        self.labelFlagIMG.setText("")
        self.labelFlagIMG.setObjectName("labelFlagIMG")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubarFileMenu = QtWidgets.QMenuBar(MainWindow)
        self.menubarFileMenu.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubarFileMenu.setObjectName("menubarFileMenu")
        self.menuFileCtryButtons = QtWidgets.QMenu(self.menubarFileMenu)
        self.menuFileCtryButtons.setObjectName("menuFileCtryButtons")
        MainWindow.setMenuBar(self.menubarFileMenu)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoadCountries = QtWidgets.QAction(MainWindow)
        self.actionLoadCountries.setObjectName("actionLoadCountries")
        self.actionSavetoFile = QtWidgets.QAction(MainWindow)
        self.actionSavetoFile.setEnabled(False)
        self.actionSavetoFile.setObjectName("actionSavetoFile")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExitButton = QtWidgets.QAction(MainWindow)
        self.actionExitButton.setObjectName("actionExitButton")
        self.menuFileCtryButtons.addAction(self.actionLoadCountries)
        self.menuFileCtryButtons.addAction(self.actionSavetoFile)
        self.menuFileCtryButtons.addSeparator()
        self.menuFileCtryButtons.addAction(self.actionExitButton)
        self.menubarFileMenu.addAction(self.menuFileCtryButtons.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Countries of the World"))
        self.LabelChooseCountryList.setText(_translate("MainWindow", "Choose a country from the List"))
        self.labelPercentageWrldPop.setText(_translate("MainWindow", "Percentage of World Population"))
        self.labelAreaIn.setText(_translate("MainWindow", "Total Area in"))
        self.comboBoxSqMilesxSqKM.setItemText(0, _translate("MainWindow", "Sq.Miles"))
        self.comboBoxSqMilesxSqKM.setItemText(1, _translate("MainWindow", "Sq.Km"))
        self.pushButtonUpdatePop.setText(_translate("MainWindow", "Update Population"))
        self.labelCountryName.setText(_translate("MainWindow", "CtryName"))
        self.labelPopulation.setText(_translate("MainWindow", "Population:"))
        self.groupBoxPopDens.setTitle(_translate("MainWindow", "Population Density"))
        self.radioButtonPopPerSQMile.setText(_translate("MainWindow", "Per Square Mile"))
        self.radioButtonPerSqKMPop.setText(_translate("MainWindow", "Per Square Km"))
        self.labelPopDensValue.setText(_translate("MainWindow", "PopValue"))
        self.labelPercentWPValue.setText(_translate("MainWindow", "PerValue"))
        self.labelTotalAreaValue.setText(_translate("MainWindow", "AreainValue"))
        self.menuFileCtryButtons.setTitle(_translate("MainWindow", "File"))
        self.actionLoadCountries.setText(_translate("MainWindow", "Load Countries"))
        self.actionSavetoFile.setText(_translate("MainWindow", "Save to File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExitButton.setText(_translate("MainWindow", "Exit"))
