#Author RICARDO OLIVEIRA - W0428722
#Create and connect do TB

# DROP DATABASE IF EXISTS Products_DDL;
# CREATE DATABASE Products_DDL;
USE Products_DDL;
# DROP TABLE IF EXISTS PRODUCT;
# DROP TABLE IF EXISTS SUPPLIER;
# DROP TABLE IF EXISTS CLOTHINGCATEGORY;
# DROP TABLE IF EXISTS CLOTHINGSIZE;
# DROP TABLE IF EXISTS COLOUR;

#TABLE AND COLUMNS CREATE
CREATE TABLE ProductCategory (
    ProductID INT,
    CategoryID INT
);
CREATE TABLE ProductSize (
    ProductID INT,
    SizeID INT
);
CREATE TABLE ProductColour (
    ProductID INT,
    ColourID INT
);
#MODIFICATIONS AND CONSTRAINTS
ALTER TABLE Product ADD CONSTRAINT fk_SupID FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID);
ALTER TABLE ProductCategory add primary key (ProductID, CategoryID);
ALTER TABLE ProductCategory ADD CONSTRAINT fk_PCat1 FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID);
ALTER TABLE ProductCategory ADD CONSTRAINT fk_PCat2 FOREIGN KEY (CategoryID) REFERENCES clothingcategory(CategoryId);
ALTER TABLE ProductSize add primary key (ProductID, SizeID);
ALTER TABLE ProductSize ADD CONSTRAINT fk_PSize1 FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID);
ALTER TABLE ProductSize ADD CONSTRAINT fk_PSize2 FOREIGN KEY (SizeID) REFERENCES clothingsize(SizeID);
ALTER TABLE ProductColour add primary key (ProductID, ColourID);
ALTER TABLE ProductColour ADD CONSTRAINT fk_PCol1 FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID);
ALTER TABLE ProductColour ADD CONSTRAINT fk_PCol2 FOREIGN KEY (ColourID) REFERENCES colour(ColourID);
